import * as THREE from 'three';
import {OrbitControls} from 'three/addons/OrbitControls.js';
const stage=document.querySelector('#stage'),status=document.querySelector('#status');
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.setClearColor(0xedf2f4);renderer.outputColorSpace=THREE.SRGBColorSpace;stage.append(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.01,500);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.4;controls.maxDistance=90;scene.add(new THREE.HemisphereLight(0xffffff,0x647985,2.3));const sun=new THREE.DirectionalLight(0xffffff,2.8);sun.position.set(10,20,15);scene.add(sun);
const colors={blocks:0xc8d1d5,columns:0x99aab2,piles:0x99aab2,beam:0x99aab2,channels:0xc4874e,grout:0x2e8ea2,mortar:0xd9c9b7,steel:0xbb4550};const names={blocks:'Blocos de alvenaria',columns:'Pilares',piles:'Estacas',beam:'Viga baldrame',channels:'Blocos canaleta',grout:'Graute das cintas',mortar:'Juntas de argamassa',steel:'Armaduras'};const items=[];let box,center,span,loaded=false;
function reset(){if(!loaded)return;controls.target.copy(center);const tangent=Math.tan(THREE.MathUtils.degToRad(camera.fov/2));const distance=Math.max(span.x/(2*tangent*camera.aspect),span.y/(2*tangent))*1.35;camera.position.set(center.x+distance*.25,center.y+distance*.20,center.z+distance);controls.maxDistance=Math.max(120,distance*2);controls.update();}
function mode(mode){for(const o of items){o.visible=mode!=='steel'||o.userData.group==='steel';const ghost=mode==='inside'&&['blocks','channels','columns','piles','beam','mortar'].includes(o.userData.group);o.material.transparent=ghost;o.material.opacity=ghost?.10:1;o.material.depthWrite=!ghost;}document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===mode));document.querySelector('#info').style.display='none';}
try{const response=await fetch('./model.json');if(!response.ok)throw Error('A geometria ainda não foi exportada do Revit.');const data=await response.json();const groups={};for(const p of data.pieces){(groups[p.group]??=[]).push(...[]);groups[p.group].push(p.vertices);}let triangles=0;for(const [group,parts]of Object.entries(groups)){const n=parts.reduce((s,p)=>s+p.length,0);const verts=new Float32Array(n);let k=0;for(const p of parts){verts.set(p,k);k+=p.length;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(verts,3));g.computeVertexNormals();const m=new THREE.MeshStandardMaterial({color:colors[group]??0x999999,roughness:group==='steel'?.38:.85,metalness:group==='steel'?.45:0,side:THREE.DoubleSide});const mesh=new THREE.Mesh(g,m);mesh.userData.group=group;scene.add(mesh);items.push(mesh);triangles+=n/9;}
box=new THREE.Box3();items.forEach(o=>box.union(new THREE.Box3().setFromObject(o)));center=box.getCenter(new THREE.Vector3());span=box.getSize(new THREE.Vector3());loaded=true;reset();status.hidden=true;document.querySelector('#badge').textContent=`${span.x.toFixed(2).replace('.',',')} m · ${data.pieces.length.toLocaleString('pt-BR')} elementos`;window.viewerQA={source:data.source,elements:data.pieces.length,triangles,bounds:{min:box.min.toArray(),max:box.max.toArray()},groups:Object.keys(groups)};
const ground=new THREE.GridHelper(34,34,0xc0d0d8,0xdde5e9);ground.position.set(center.x,.3,0);ground.material.transparent=true;ground.material.opacity=.35;scene.add(ground);
}catch(err){status.textContent=err.message;document.querySelector('#badge').textContent='Modelo não disponível';console.error(err);}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>mode(b.dataset.mode));document.querySelector('#reset').onclick=reset;document.querySelector('#share').onclick=()=>{const qr=document.querySelector('#qr');qr.style.display=qr.style.display==='block'?'none':'block';};
const focus=document.createElement('button');focus.textContent='+';focus.title='Aproximar trecho central';focus.setAttribute('aria-label','Aproximar trecho central');document.querySelector('nav').insertBefore(focus,document.querySelector('#reset'));focus.onclick=()=>{if(!loaded)return;controls.target.copy(center);camera.position.set(center.x+3,center.y+3.5,center.z+14);controls.update();};
let walking=false,yaw=0,pitch=0,lookPointer=null;const held=new Set();
const walkButton=document.querySelector('#walk');walkButton.textContent=loaded?'Caminhar':'Modelo indisponível';walkButton.disabled=!loaded;
const pad=document.createElement('div');pad.style.cssText='position:absolute;bottom:105px;right:20px;display:none;grid-template-columns:repeat(3,42px);gap:5px;z-index:3;touch-action:none';
for(const [key,label,col] of [['w','↑',2],['a','←',1],['s','↓',2],['d','→',3]]){const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-label',{w:'Avançar',a:'Mover para esquerda',s:'Recuar',d:'Mover para direita'}[key]);b.style.cssText=`padding:12px;background:white;grid-column:${col};touch-action:none`;b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);held.add(key);};b.onpointerup=b.onpointercancel=()=>held.delete(key);pad.append(b);}document.body.append(pad);
function setWalking(on){if(!loaded)return;walking=on;held.clear();controls.enabled=!on;pad.style.display=on?'grid':'none';walkButton.textContent=on?'Sair da caminhada':'Caminhar';document.querySelector('.help').style.display=on?'none':'';camera.fov=on?60:35;camera.updateProjectionMatrix();if(on){camera.position.set(1,1.95,3);yaw=0;pitch=0;camera.rotation.set(pitch,yaw,0,'YXZ');}else reset();}
walkButton.onclick=()=>setWalking(!walking);document.querySelector('#reset').onclick=()=>setWalking(false);
if(new URLSearchParams(location.search).get('walk')==='1'&&loaded)setWalking(true);
addEventListener('keydown',e=>{if(walking&&['w','a','s','d','ArrowUp','ArrowLeft','ArrowDown','ArrowRight'].includes(e.key)){e.preventDefault();held.add(({ArrowUp:'w',ArrowLeft:'a',ArrowDown:'s',ArrowRight:'d'})[e.key]??e.key);}});addEventListener('keyup',e=>held.delete(({ArrowUp:'w',ArrowLeft:'a',ArrowDown:'s',ArrowRight:'d'})[e.key]??e.key));addEventListener('blur',()=>held.clear());
renderer.domElement.addEventListener('pointerdown',e=>{if(walking){lookPointer={id:e.pointerId,x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);}});renderer.domElement.addEventListener('pointermove',e=>{if(!walking||!lookPointer||e.pointerId!==lookPointer.id)return;yaw-=(e.clientX-lookPointer.x)*.004;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-lookPointer.y)*.004,-1.2,1.2);lookPointer.x=e.clientX;lookPointer.y=e.clientY;camera.rotation.set(pitch,yaw,0,'YXZ');});renderer.domElement.addEventListener('pointerup',()=>lookPointer=null);renderer.domElement.addEventListener('pointercancel',()=>lookPointer=null);
let start;renderer.domElement.addEventListener('pointerdown',e=>{start=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(!start||Math.hypot(e.clientX-start[0],e.clientY-start[1])>5)return;const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1),camera);const hit=ray.intersectObjects(items.filter(o=>o.visible&&o.material.opacity>.5))[0];const info=document.querySelector('#info');if(hit){info.textContent=names[hit.object.userData.group];info.style.display='block';}else info.style.display='none';});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});let lastTime=performance.now();renderer.setAnimationLoop(()=>{const now=performance.now(),dt=Math.min((now-lastTime)/1000,.05);lastTime=now;if(walking){const f=(held.has('w')?1:0)-(held.has('s')?1:0),r=(held.has('d')?1:0)-(held.has('a')?1:0);const v=new THREE.Vector3(r,0,-f);if(v.lengthSq()){v.normalize().applyAxisAngle(THREE.Object3D.DEFAULT_UP,yaw).multiplyScalar(1.4*dt);const next=camera.position.clone().add(v);next.x=THREE.MathUtils.clamp(next.x,-3,29);next.z=THREE.MathUtils.clamp(next.z,-10,10);if(next.x>-.4&&next.x<26.4&&Math.abs(next.z)<.4)next.z=camera.position.z<0?-.4:.4;camera.position.copy(next);}camera.position.y=1.95;}else controls.update();renderer.render(scene,camera);});
